# 生成图案中文名表（Core 侧可离线用）：<mod>/Core/Registry/PatternNames.Generated.cs
#
# 为什么要生成：咒法学之书里只有图案 id（`get_caster` 这种英文 op 名），
# 而原版的正式名称是中文的「意识之精思」。玩家记的是名字，不是 `entity_pos/eye`。
#
# 名字来源两条，按优先级：
#   1. _tools/pattern_names_zh.json —— 从 HexMod 官方 zh_cn.flatten.json5 抽出的**完整**
#      译名表（190 条），由 _tools/lang2names.mjs 生成（原文件是 JSON5，见该脚本注释）。
#      刷新：浏览器存下
#        https://raw.githubusercontent.com/gamma-delta/HexMod/main/Common/src/main/resources/assets/hexcasting/lang/zh_cn.flatten.json5
#      再 node _tools/lang2names.mjs <存下的文件> _tools/pattern_names_zh.json
#   2. 「图案工具/patdb.json」—— 用户提供的图案库，官方表缺项时兜底。
#
# 匹配一律按 **op（也就是我们的图案 id）**，最后才退化到签名。只按签名不行：
# 同一签名可能对应多条（起始方向不同），且 patdb 400 条里有 140 条根本没签名。
$ErrorActionPreference = 'Stop'

$toolsDir = $PSScriptRoot
$modRoot  = Join-Path (Split-Path -Parent $toolsDir) "HexCastingTerraria"
$langPath = Join-Path $toolsDir "pattern_names_zh.json"
$dbPath   = "D:\DeepSeekHarness\图案工具\patdb.json"
$dataFile = Join-Path $modRoot "Core\Registry\GeneratedPatternData.cs"
$outPath  = Join-Path $modRoot "Core\Registry\PatternNames.Generated.cs"

if (-not (Test-Path $dataFile)) { throw "找不到图案数据表：$dataFile" }

# ---- 官方语言文件（首选）----
$byId = @{}
if (Test-Path $langPath) {
    $lang = Get-Content -LiteralPath $langPath -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($p in $lang.PSObject.Properties) { $byId[$p.Name] = $p.Value }
}

# ---- patdb（兜底）----
$byOp = @{}
$bySig = @{}
if (Test-Path $dbPath) {
    foreach ($e in (Get-Content -LiteralPath $dbPath -Raw -Encoding UTF8 | ConvertFrom-Json)) {
        if (-not $e.cn) { continue }
        if ($e.op -and -not $byOp.ContainsKey($e.op)) { $byOp[$e.op] = $e.cn }
        if ($e.sig -and -not $bySig.ContainsKey($e.sig)) { $bySig[$e.sig] = $e.cn }
    }
}

# ---- 我们的 188 条 ----
$text = Get-Content -LiteralPath $dataFile -Raw
$rows = @()
foreach ($m in [regex]::Matches($text, 'new PatternData\("([^"]+)", "([^"]*)", HexDir\.(\w+), "([^"]*)"\)')) {
    $rows += [pscustomobject]@{
        Id  = $m.Groups[1].Value
        Sig = $m.Groups[2].Value
        Op  = $m.Groups[4].Value
    }
}

$langHit = 0; $byOpHit = 0; $bySigHit = 0
$names = [ordered]@{}
$miss = @()
foreach ($r in $rows) {
    if ($byId.ContainsKey($r.Id))        { $names[$r.Id] = $byId[$r.Id]; $langHit++; continue }
    if ($byOp.ContainsKey($r.Id))        { $names[$r.Id] = $byOp[$r.Id]; $byOpHit++; continue }
    if ($r.Sig -and $bySig.ContainsKey($r.Sig)) { $names[$r.Id] = $bySig[$r.Sig]; $bySigHit++; continue }
    $miss += $r.Id
}

# ---- 生成 C# ----
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// <auto-generated>")
[void]$sb.AppendLine("//     由 _tools/gen_pattern_names.ps1 生成，**不要手改**。")
[void]$sb.AppendLine("//     名字来自 HexMod 官方 lang/zh_cn.flatten.json5（经 _tools/lang2names.mjs 抽取），")
[void]$sb.AppendLine("//     缺项由「图案工具/patdb.json」兜底。改名字请改数据源后重新生成。")
[void]$sb.AppendLine("// </auto-generated>")
# 自动生成的文件默认不在 nullable 上下文里，而下面签名用了 string?，不加这句会有 CS8669 警告
[void]$sb.AppendLine("#nullable enable")
[void]$sb.AppendLine("using System.Collections.Generic;")
[void]$sb.AppendLine()
[void]$sb.AppendLine("namespace HexCastingTerraria.Core.Registry;")
[void]$sb.AppendLine()
[void]$sb.AppendLine("/// <summary>")
[void]$sb.AppendLine("/// 图案的**正式中文名**（例如 `get_caster` → 「意识之精思」）。")
[void]$sb.AppendLine("///")
[void]$sb.AppendLine("/// 来源：原版语言文件的官方译名。咒法学之书与临摹引导用它替代裸 id ——")
[void]$sb.AppendLine("/// 玩家记的是名字（「内省」「闪现」），不是 `open_paren`、`blink`。")
[void]$sb.AppendLine("///")
[void]$sb.AppendLine("/// 没收录的图案查不到就返回 null，调用方回落显示 id，**不会报错**。")
[void]$sb.AppendLine("/// </summary>")
[void]$sb.AppendLine("public static class GeneratedPatternNames")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    public static readonly Dictionary<string, string> ById = new()")
[void]$sb.AppendLine("    {")
foreach ($key in ($names.Keys | Sort-Object)) {
    $v = $names[$key] -replace '"', '\"'
    [void]$sb.AppendLine("        [`"$key`"] = `"$v`",")
}
[void]$sb.AppendLine("    };")
[void]$sb.AppendLine()
[void]$sb.AppendLine("    /// <summary>查名字。没有就返回 null（调用方回落显示 id）。</summary>")
[void]$sb.AppendLine("    public static string? NameOf(string patternId)")
[void]$sb.AppendLine("        => ById.TryGetValue(patternId, out var name) ? name : null;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine()

[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($true)))

"图案总数          : $($rows.Count)"
"官方译名直接命中  : $langHit"
"patdb(op) 兜底    : $byOpHit"
"patdb(签名) 兜底  : $bySigHit"
"共收录            : $($names.Count)"
"仍无名字          : $($miss.Count)"
if ($miss.Count -gt 0) { "  " + ($miss -join ', ') }
"已写出            : $outPath"
