# 生成 ARCHITECTURE.md —— 全项目**唯一**的架构入口。
#
# 为什么要有它：源码 130+ 文件 / 2 万行，文档 20+ 篇 / 400 KB。
# 没有任何单次上下文能塞下全部 —— 所以"让 AI 完全理解架构"不能靠"把所有东西读一遍"，
# 只能靠**一个短、准、且与代码强绑定的入口**。
#
# 本文件的内容全部从代码派生（分层、每个文件的一句话职责、单一真源表），
# 所以它不会腐化：改了代码重跑一次就同步。
#
# 用法：.\gen_architecture.ps1
$ErrorActionPreference = 'Stop'

$tools = $PSScriptRoot
$mod   = Join-Path (Split-Path -Parent $tools) 'HexCastingTerraria'
$enc   = New-Object System.Text.UTF8Encoding($false)

# 从文件头注释里抽"一句话职责"：
#   优先取 XML 文档注释 `<summary>` 之后的第一行非空 `///`；
#   没有就取第一个 `//` 注释行；都没有就标记出来（这也是文档覆盖率指标）。
function Get-Responsibility($path) {
    $lines = Get-Content -LiteralPath $path -TotalCount 60
    $inSummary = $false
    foreach ($l in $lines) {
        $t = $l.Trim()
        if ($t -match '^///\s*<summary>') {
            $rest = ($t -replace '^///\s*<summary>', '').Trim()
            if ($rest -ne '' -and $rest -notmatch '^</summary>') { return $rest }
            $inSummary = $true
            continue
        }
        if ($inSummary) {
            if ($t -match '^///\s*</summary>') { break }
            $body = ($t -replace '^///', '').Trim()
            if ($body -ne '') { return $body }
        }
    }
    foreach ($l in $lines) {
        $t = $l.Trim()
        if ($t -match '^//\s*(.+)$') {
            $body = $Matches[1].Trim()
            if ($body -ne '' -and $body -notmatch '^<auto-generated') { return $body }
        }
    }
    return ''
}

$outer = Split-Path -Parent $mod
$layers = [ordered]@{
    'Config'  = '模组配置（依赖 tModLoader，所以**不在 Core 里**）'
    'Core'    = '纯逻辑：栈机 / 图案 / 几何 / 世界接口 / UI 布局数学。**不得引用 XNA 与 tModLoader**'
    'Content' = '泰拉侧实现：物品、方块、玩家、世界适配'
    'Client'  = '客户端表现：画布、书、HUD、调试叠加层'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('  本文档由 _tools/gen_architecture.ps1 从代码生成 —— **不要手改**。')
[void]$sb.AppendLine('  改了代码请重跑生成器；_tools/check_arch.ps1 会核对文档与代码是否一致。')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine()
[void]$sb.AppendLine('# 架构入口')
[void]$sb.AppendLine()
[void]$sb.AppendLine('这是**唯一**的架构入口。源码 2 万行塞不进任何单次上下文，所以这里只放三样东西：')
[void]$sb.AppendLine('分层与依赖方向、每个文件的一句话职责、以及"什么住在哪里"的单一真源表。')
[void]$sb.AppendLine('**会过期的数字**（图案数、测试数、包体）一律不在这里，去 [STATUS.generated.md](STATUS.generated.md)。')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## 1. 分层与依赖方向（可机械校验）')
[void]$sb.AppendLine()
[void]$sb.AppendLine('```')
[void]$sb.AppendLine('        Client/  ──┐')
[void]$sb.AppendLine('                  ├──▶  Core/        （Core 谁都不依赖）')
[void]$sb.AppendLine('        Content/ ─┤')
[void]$sb.AppendLine('                  │')
[void]$sb.AppendLine('        Config/  ─┘')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('禁止：Core →(Content|Client|Config)、Content → Client')
[void]$sb.AppendLine('```')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| 层 | 职责 |')
[void]$sb.AppendLine('|---|---|')
foreach ($k in $layers.Keys) { [void]$sb.AppendLine("| ``$k/`` | $($layers[$k]) |") }
[void]$sb.AppendLine()
[void]$sb.AppendLine('这两条约束由 `_tools/check_arch.ps1` **零白名单**强制。')
[void]$sb.AppendLine('（曾经有 3 个例外被写进文档当成"设计如此" —— 违规一旦被文档化，')
[void]$sb.AppendLine('读文档的人就会认为那是规范，永远不会去修。所以例外清零、断言收紧。）')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## 2. 每个文件的一句话职责')
[void]$sb.AppendLine()
[void]$sb.AppendLine('从文件头注释自动提取。**空职责那几行就是文档缺口**。')
[void]$sb.AppendLine()

$noDoc = New-Object System.Collections.Generic.List[string]
$totalFiles = 0

foreach ($layer in $layers.Keys) {
    $dir = Join-Path $mod $layer
    if (-not (Test-Path $dir)) { continue }
    [void]$sb.AppendLine("### $layer/")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| 文件 | 职责 |')
    [void]$sb.AppendLine('|---|---|')
    $files = Get-ChildItem $dir -Recurse -File -Filter *.cs |
             Where-Object { $_.FullName -notmatch '\\(obj|bin)\\' } | Sort-Object FullName
    foreach ($f in $files) {
        $totalFiles++
        $rel = $f.FullName.Replace("$dir\", '').Replace('\', '/')
        $resp = Get-Responsibility $f.FullName
        if ($resp -eq '') {
            $noDoc.Add("$layer/$rel")
            $resp = '**（无文件头说明）**'
        }
        [void]$sb.AppendLine("| ``$rel`` | $resp |")
    }
    [void]$sb.AppendLine()
}

# 根目录的 .cs（模组入口等）
$rootCs = Get-ChildItem $mod -File -Filter *.cs | Sort-Object Name
if ($rootCs.Count -gt 0) {
    [void]$sb.AppendLine('### （模组根目录）')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| 文件 | 职责 |')
    [void]$sb.AppendLine('|---|---|')
    foreach ($f in $rootCs) {
        $totalFiles++
        $resp = Get-Responsibility $f.FullName
        if ($resp -eq '') { $noDoc.Add($f.Name); $resp = '**（无文件头说明）**' }
        [void]$sb.AppendLine("| ``$($f.Name)`` | $resp |")
    }
    [void]$sb.AppendLine()
}

[void]$sb.AppendLine('## 3. 单一真源表（改东西之前先看这里）')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| 事实 | 唯一出处 | 别处不许重定义 |')
[void]$sb.AppendLine('|---|---|---|')
[void]$sb.AppendLine('| 图案清单（id / 签名 / 起始方向） | `Core/Registry/GeneratedPatternData.cs` | 任何地方手写图案串 |')
[void]$sb.AppendLine('| 图案中文名 | `Core/Registry/PatternNames.Generated.cs` | 界面里硬写名字 |')
[void]$sb.AppendLine('| 图案行为注册 | `Core/Casting/Actions/*.cs` 的 `RegisterAll()` | 在别处 `RegisterAction` |')
[void]$sb.AppendLine('| 坐标换算 / 网格几何 | `Core/Casting/Math/HexGrid.cs` | 手抄一份公式（**曾经发生过**） |')
[void]$sb.AppendLine('| 书的布局 / 格子命中 | `Core/Ui/BookLayout.cs` | 在 HexBook 里再写一遍 col/row（**曾经发生过**） |')
[void]$sb.AppendLine('| 画布吸附阈值 | `Client/UI/HexCanvas.cs` + `Config/HexClientConfig.cs`（默认 0.5，对齐原版） | 任何第三处默认值 |')
[void]$sb.AppendLine('| 世界接口 | `Core/Casting/Eval/ICastingWorld.cs` | Content 里另立接口 |')
[void]$sb.AppendLine('| 当前状态数字 | `STATUS.generated.md`（生成） | 任何手写文档复述数字 |')
[void]$sb.AppendLine('| 架构约束 | `_tools/check_arch.ps1`（可执行断言） | 文档里写"我们约定…" |')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## 4. 怎么验一遍')
[void]$sb.AppendLine()
[void]$sb.AppendLine('```powershell')
[void]$sb.AppendLine('cd D:\DeepSeekHarness\tmod')
[void]$sb.AppendLine('.\_tools\run_all.ps1      # 编译 → 离线 VM → 拖拽/几何 → 生成状态表 → 架构断言')
[void]$sb.AppendLine('```')
[void]$sb.AppendLine()
[void]$sb.AppendLine('被验证覆盖不到的层（渲染、输入、联机、存档）见 [STATUS.generated.md](STATUS.generated.md) 的最后一节。')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## 5. 参考实现')
[void]$sb.AppendLine()
[void]$sb.AppendLine('原版咒法学源码在 `D:\DeepSeekHarness\hexsrc`（Kotlin/Java）。')
[void]$sb.AppendLine('**凡是有疑问的地方，以原版源码为准，不要以本模组的注释为准** ——')
[void]$sb.AppendLine('本模组已经出现过几次"注释写的语义和原版相反"（`tileNoFail`、`draw.py` 的段数）。')

[System.IO.File]::WriteAllText((Join-Path (Split-Path -Parent $mod) 'ARCHITECTURE.md'), $sb.ToString(), $enc)
"已写出 ARCHITECTURE.md：$totalFiles 个文件；其中 $($noDoc.Count) 个缺文件头说明"
if ($noDoc.Count -gt 0) {
    "缺说明的文件（前 10 个）："
    $noDoc | Select-Object -First 10 | ForEach-Object { "  $_" }
}
