"""生成 35 种颜料（染色剂）的贴图与物品类（可重复运行）。

来源：本地原版 jar 的 textures/item/colorizer/*.png + .mcmeta（HexMod v0.11.4，MIT）。
原版颜料贴图是 MC 的动画贴图：竖排若干帧，.mcmeta 给每帧显示几刻（每帧时长不一样）。
泰拉的 DrawAnimationVertical 只支持等长帧，所以这里把动画**按 MC 刻展开**：
每个 MC 刻输出一帧（一帧显示 N 刻就重复 N 次），运行时每帧 3 个泰拉刻（60 帧 = MC 20 刻），
播放节奏与原版完全一致。物品照例最近邻 ×2。

输出：
  HexCastingTerraria/Content/Items/Pigments/<类名>.png
  HexCastingTerraria/Content/Items/PigmentItems.Generated.cs   （每种颜料一个类：颜料 id + 帧数）
"""
import json
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAR = os.path.join(os.path.dirname(ROOT), 'hexwork', 'jar', 'assets', 'hexcasting', 'textures', 'item', 'colorizer')
MOD = os.path.join(ROOT, 'HexCastingTerraria', 'Content', 'Items')

DYES = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray',
        'light_gray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black']
PRIDE = ['agender', 'aroace', 'aromantic', 'asexual', 'bisexual', 'demiboy', 'demigirl', 'gay',
         'genderfluid', 'genderqueer', 'intersex', 'lesbian', 'nonbinary', 'pansexual', 'plural', 'transgender']


def camel(s):
    return ''.join(p.capitalize() for p in s.split('_'))


# (类名, 颜料 id, 贴图文件名)
PIGMENTS = ([(f'PigmentDye{camel(d)}', f'dye_{d}', f'dye_{d}') for d in DYES]
            + [(f'PigmentPride{camel(p)}', f'pride_{p}', f'pride_{p}') for p in PRIDE]
            + [('PigmentDefault', 'default', 'default'),
               ('PigmentAncient', 'ancient', 'ancient'),
               ('PigmentSoulglimmer', 'uuid', 'uuid')])


def bake(name):
    """按 .mcmeta 把动画展开成「每 MC 刻一帧」的竖排图集（×2）。返回 (图, 帧数)。"""
    im = Image.open(os.path.join(JAR, name + '.png')).convert('RGBA')
    n = im.height // 16
    frames = [(i, 1) for i in range(n)]
    meta = os.path.join(JAR, name + '.png.mcmeta')
    if os.path.exists(meta):
        anim = json.load(open(meta, encoding='utf-8'))['animation']
        default_time = anim.get('frametime', 1)
        spec = anim.get('frames')
        if spec:
            frames = [(f, default_time) if isinstance(f, int) else (f['index'], f.get('time', default_time)) for f in spec]
        else:
            frames = [(i, default_time) for i in range(n)]
    ticks = [idx for idx, t in frames for _ in range(t)]
    out = Image.new('RGBA', (32, 32 * len(ticks)), (0, 0, 0, 0))
    for k, idx in enumerate(ticks):
        cell = im.crop((0, idx * 16, 16, idx * 16 + 16)).resize((32, 32), Image.NEAREST)
        out.paste(cell, (0, 32 * k))
    return out, len(ticks)


lines = [
    '// <auto-generated> 由 _tools/gen_pigments.py 生成，不要手改。</auto-generated>',
    '// 35 种颜料（原版 ItemDyePigment ×16、ItemPridePigment ×16、空无 / 远古 / 灵魂闪光）。',
    '// 行为都在基类 PigmentItem 里；这里每个类只给出颜料 id 与贴图帧数（按 MC 刻展开后的帧数）。',
    'namespace HexCastingTerraria.Content.Items;',
    '',
]
os.makedirs(os.path.join(MOD, 'Pigments'), exist_ok=True)
for cls, pid, tex in PIGMENTS:
    sheet, count = bake(tex)
    sheet.save(os.path.join(MOD, 'Pigments', cls + '.png'))
    lines.append(f'public sealed class {cls} : PigmentItem {{ public override string PigmentId => "{pid}"; '
                 f'protected override int FrameCount => {count}; }}')
lines.append('')
with open(os.path.join(MOD, 'PigmentItems.Generated.cs'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print(f'写出 {len(PIGMENTS)} 种颜料')
