# 从上游 Hexcessible 的 numbers.txt（逗号分隔，第 i 项是数字 i+1 在「数字之精思」前缀后面的笔顺）生成 C# 表。
# 用法：python _tools/gen_hexcessible_numbers.py
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = r'D:/DeepSeekHarness/addons_src/hexcessible/src/main/resources/numbers.txt'
OUT = os.path.join(ROOT, 'HexCastingTerraria', 'Addons', 'Hexcessible', 'Core', 'NumberTable.Generated.cs')

parts = open(SRC, encoding='utf-8').read().strip().split(',')
assert len(parts) == 2000 and all(set(p) <= set('qweasd') for p in parts)
lines = []
for i in range(0, len(parts), 16):
    lines.append('        ' + ' '.join('"%s",' % p for p in parts[i:i + 16]))
body = '\n'.join(lines)
text = '''// <auto-generated> 由 _tools/gen_hexcessible_numbers.py 从上游 Hexcessible 0.3.1 的 numbers.txt 生成，不要手改。</auto-generated>
namespace HexCastingTerraria.Addons.Hexcessible.Core;

/// <summary>上游 numbers.txt：第 i 项是数字 i + 1 在「数字之精思」前缀（aqaa / dedd）后面的最短笔顺，共 2000 项。</summary>
public static class NumberTable
{
    public static readonly string[] Suffix =
    {
%s
    };
}
''' % body
open(OUT, 'w', encoding='utf-8', newline='\n').write(text)
print('wrote', OUT, len(parts))
