# 生成附属的书页：Addons/<附属>/Core/<附属>Book.Generated.cs —— 往咒法学之书里加分类 / 条目。
#
# 输入（都是上游原文，不手写正文）：
#   附属 jar 里的 assets/hexcasting/patchouli_books/thehexbook/en_us/{categories,entries}   手册结构
#   附属 jar 里的官方中文（lang/zh_cn.json 或 zh_cn.flatten.json5），缺的键回退到本体的中文 / 英文
#
# 生成的 AddTo(doc)：
#   - 附属自己的分类：新建（父分类照上游，例如 HexParse 指令挂在「咒法学」下面）
#   - 进本体已有分类的条目（例如 HexParse 的图案条目进「图案」）：加进去后按原版的顺序重排
#   - 物品图标 / 页面写法和本体生成器（gen_book_content.py）一模一样，直接复用它的函数
# 附属开着才调用（HexAddon.AddBookContent），关着的附属在书里不存在。
#
# 用法：python _tools/gen_addon_book.py hexparse
import json, os, sys, zipfile
sys.path.insert(0, os.path.dirname(__file__))
import gen_book_content as base
import hexlang

ADDONS = os.path.join(base.ROOT, 'tmod/HexCastingTerraria/Addons')
BOOK_PREFIX = 'assets/hexcasting/patchouli_books/thehexbook/en_us/'

# 附属 id -> (目录名, 中文语言文件在 jar 里的路径)
SPECS = {
    'hexparse': ('HexParse', 'assets/hexparse/lang/zh_cn.json'),
}

# 附属书页里新出现的图标（MC 物品 -> 泰拉对应物），合并进本体的映射
EXTRA_ITEMS = {
    'minecraft:command_block': 'Terraria:Sign',
}


def main(addon_id):
    folder, zh_path = SPECS[addon_id]
    manifest = json.load(open(os.path.join(ADDONS, folder, 'addon.json'), encoding='utf-8'))
    jar = zipfile.ZipFile(manifest['upstream']['jar'])
    base.ITEM_MAP.update(EXTRA_ITEMS)

    raw = jar.read(zh_path).decode('utf-8')
    addon_zh = json.loads(raw) if zh_path.endswith('.json') else hexlang.loads(raw)
    t_base, missing = base.load_lang()

    def t(key):
        return addon_zh[key] if key in addon_zh else t_base(key)

    cats, entries = [], []
    for name in sorted(jar.namelist()):
        if not name.startswith(BOOK_PREFIX) or not name.endswith('.json'):
            continue
        rel = name[len(BOOK_PREFIX):]
        data = json.loads(jar.read(name).decode('utf-8'))
        if rel.startswith('categories/'):
            data['id'] = rel[len('categories/'):-5]
            cats.append(data)
        elif rel.startswith('entries/'):
            if 'flag' in data:
                continue
            data['id'] = rel[len('entries/'):-5]
            entries.append(data)

    unmapped = set()
    out = []
    w = out.append
    w('// <auto-generated>')
    w('//     本文件由 _tools/gen_addon_book.py 生成，**不要手改**：改生成器，然后重新跑脚本。')
    w(f'//     内容：{manifest["name"]} {manifest["upstream"]["version"]}（{manifest["upstream"]["license"]}）的书页结构 + 官方简体中文。')
    w('// </auto-generated>')
    w('#nullable enable')
    w('using HexCastingTerraria.Core.Ui;')
    w('')
    w(f'namespace HexCastingTerraria.Addons.{folder}.Core;')
    w('')
    w(f'public static class {folder}Book')
    w('{')
    w('    public static void AddTo(BookDocument doc)')
    w('    {')
    w('        BookCategory? c;')
    w('        BookEntry e;')
    w('        BookPage p;')
    for c in cats:
        icon = base.item_key(c.get('icon'))
        if not icon:
            unmapped.add(c.get('icon'))
        w('')
        w(f'        c = new BookCategory {{ Id = {base.cs(c["id"])}, NameKey = {base.cs(c["name"])}, DisplayName = {base.cs(t(c["name"]))}, '
          f'IconItem = {base.cs(icon)}, DescriptionKey = {base.cs(c["description"])}, DisplayDescription = {base.cs(t(c["description"]))}, '
          f'SortNum = {c.get("sortnum", 0)}, ParentId = {base.cs(c.get("parent", "").split(":", 1)[-1])} }};')
        w('        doc.Categories.Add(c);')
    touched = []
    for e in sorted(entries, key=lambda e: (e['category'], not e.get('priority', False), e.get('sortnum', 0), t(e['name']))):
        cat = e['category'].split(':', 1)[1]
        if cat not in touched:
            touched.append(cat)
        icon = base.item_key(e.get('icon'))
        if not icon:
            unmapped.add(e.get('icon'))
        color = int(e['entry_color'], 16) if 'entry_color' in e else -1
        w('')
        w(f'        c = doc.FindCategory({base.cs(cat)});')
        w('        if (c != null)')
        w('        {')
        w(f'            e = new BookEntry {{ Id = {base.cs(e["id"])}, CategoryId = {base.cs(cat)}, NameKey = {base.cs(e["name"])}, '
          f'DisplayName = {base.cs(t(e["name"]))}, IconItem = {base.cs(icon)}, SortNum = {e.get("sortnum", 0)}, '
          f'Advancement = {base.cs(e.get("advancement", ""))}, EntryColor = {color}, Priority = {str(e.get("priority", False)).lower()}, '
          f'Secret = {str(e.get("secret", False)).lower()} }};')
        w('            c.Entries.Add(e);')
        for pg in e['pages']:
            if isinstance(pg, str):
                pg = {'type': 'patchouli:text', 'text': pg}
            sub = []
            base.emit_page(sub.append, pg, t, unmapped)
            for line in sub:
                w('    ' + line)
            w('            e.Pages.Add(p);')
        w('        }')
    w('')
    w('        // 进了本体分类的条目按原版的顺序重排（priority 在前，再按 sortnum，再按名字）')
    for cat in touched:
        w(f'        doc.FindCategory({base.cs(cat)})?.Entries.Sort(BookEntryOrder.Compare);')
    w('        doc.RebuildIndex();')
    w('    }')
    w('}')
    target = os.path.join(ADDONS, folder, 'Core', f'{folder}Book.Generated.cs')
    open(target, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print(f'{manifest["name"]} 书页：新分类 {len(cats)} / 条目 {len(entries)} -> {target}')
    if unmapped:
        print(f'  没有泰拉对应物、不画图标：{sorted(x for x in unmapped if x)}')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'hexparse')
