// <auto-generated> 由 _tools/gen_pigments.py 生成，不要手改。</auto-generated>
// 35 种颜料（原版 ItemDyePigment ×16、ItemPridePigment ×16、空无 / 远古 / 灵魂闪光）。
// 行为都在基类 PigmentItem 里；这里每个类只给出颜料 id 与贴图帧数（按 MC 刻展开后的帧数）。
namespace HexCastingTerraria.Content.Items;

public sealed class PigmentDyeWhite : PigmentItem { public override string PigmentId => "dye_white"; protected override int FrameCount => 58; }
public sealed class PigmentDyeOrange : PigmentItem { public override string PigmentId => "dye_orange"; protected override int FrameCount => 58; }
public sealed class PigmentDyeMagenta : PigmentItem { public override string PigmentId => "dye_magenta"; protected override int FrameCount => 58; }
public sealed class PigmentDyeLightBlue : PigmentItem { public override string PigmentId => "dye_light_blue"; protected override int FrameCount => 58; }
public sealed class PigmentDyeYellow : PigmentItem { public override string PigmentId => "dye_yellow"; protected override int FrameCount => 58; }
public sealed class PigmentDyeLime : PigmentItem { public override string PigmentId => "dye_lime"; protected override int FrameCount => 58; }
public sealed class PigmentDyePink : PigmentItem { public override string PigmentId => "dye_pink"; protected override int FrameCount => 58; }
public sealed class PigmentDyeGray : PigmentItem { public override string PigmentId => "dye_gray"; protected override int FrameCount => 58; }
public sealed class PigmentDyeLightGray : PigmentItem { public override string PigmentId => "dye_light_gray"; protected override int FrameCount => 58; }
public sealed class PigmentDyeCyan : PigmentItem { public override string PigmentId => "dye_cyan"; protected override int FrameCount => 58; }
public sealed class PigmentDyePurple : PigmentItem { public override string PigmentId => "dye_purple"; protected override int FrameCount => 58; }
public sealed class PigmentDyeBlue : PigmentItem { public override string PigmentId => "dye_blue"; protected override int FrameCount => 58; }
public sealed class PigmentDyeBrown : PigmentItem { public override string PigmentId => "dye_brown"; protected override int FrameCount => 58; }
public sealed class PigmentDyeGreen : PigmentItem { public override string PigmentId => "dye_green"; protected override int FrameCount => 58; }
public sealed class PigmentDyeRed : PigmentItem { public override string PigmentId => "dye_red"; protected override int FrameCount => 58; }
public sealed class PigmentDyeBlack : PigmentItem { public override string PigmentId => "dye_black"; protected override int FrameCount => 58; }
public sealed class PigmentPrideAgender : PigmentItem { public override string PigmentId => "pride_agender"; protected override int FrameCount => 59; }
public sealed class PigmentPrideAroace : PigmentItem { public override string PigmentId => "pride_aroace"; protected override int FrameCount => 52; }
public sealed class PigmentPrideAromantic : PigmentItem { public override string PigmentId => "pride_aromantic"; protected override int FrameCount => 52; }
public sealed class PigmentPrideAsexual : PigmentItem { public override string PigmentId => "pride_asexual"; protected override int FrameCount => 59; }
public sealed class PigmentPrideBisexual : PigmentItem { public override string PigmentId => "pride_bisexual"; protected override int FrameCount => 66; }
public sealed class PigmentPrideDemiboy : PigmentItem { public override string PigmentId => "pride_demiboy"; protected override int FrameCount => 66; }
public sealed class PigmentPrideDemigirl : PigmentItem { public override string PigmentId => "pride_demigirl"; protected override int FrameCount => 66; }
public sealed class PigmentPrideGay : PigmentItem { public override string PigmentId => "pride_gay"; protected override int FrameCount => 52; }
public sealed class PigmentPrideGenderfluid : PigmentItem { public override string PigmentId => "pride_genderfluid"; protected override int FrameCount => 52; }
public sealed class PigmentPrideGenderqueer : PigmentItem { public override string PigmentId => "pride_genderqueer"; protected override int FrameCount => 66; }
public sealed class PigmentPrideIntersex : PigmentItem { public override string PigmentId => "pride_intersex"; protected override int FrameCount => 42; }
public sealed class PigmentPrideLesbian : PigmentItem { public override string PigmentId => "pride_lesbian"; protected override int FrameCount => 52; }
public sealed class PigmentPrideNonbinary : PigmentItem { public override string PigmentId => "pride_nonbinary"; protected override int FrameCount => 59; }
public sealed class PigmentPridePansexual : PigmentItem { public override string PigmentId => "pride_pansexual"; protected override int FrameCount => 66; }
public sealed class PigmentPridePlural : PigmentItem { public override string PigmentId => "pride_plural"; protected override int FrameCount => 59; }
public sealed class PigmentPrideTransgender : PigmentItem { public override string PigmentId => "pride_transgender"; protected override int FrameCount => 66; }
public sealed class PigmentDefault : PigmentItem { public override string PigmentId => "default"; protected override int FrameCount => 33; }
public sealed class PigmentAncient : PigmentItem { public override string PigmentId => "ancient"; protected override int FrameCount => 58; }
public sealed class PigmentSoulglimmer : PigmentItem { public override string PigmentId => "uuid"; protected override int FrameCount => 41; }
