// <auto-generated>
//     本文件由 _tools/gen_addon_book.py 生成，**不要手改**：改生成器，然后重新跑脚本。
//     内容：HexParse 1.20.1-1.11.2（MIT）的书页结构 + 官方简体中文。
// </auto-generated>
#nullable enable
using HexCastingTerraria.Core.Ui;

namespace HexCastingTerraria.Addons.HexParse.Core;

public static class HexParseBook
{
    public static void AddTo(BookDocument doc)
    {
        BookCategory? c;
        BookEntry e;
        BookPage p;

        c = new BookCategory { Id = "hexparse/commands", NameKey = "hexparse.category.commands", DisplayName = "HexParse指令", IconItem = "Terraria:Sign", DescriptionKey = "hexparse.category.commands.desc", DisplayDescription = "我如何利用来自$(thing)HexParse/$的异端之力", SortNum = 0, ParentId = "casting" };
        doc.Categories.Add(c);

        c = doc.FindCategory("hexparse/commands");
        if (c != null)
        {
            e = new BookEntry { Id = "hexparse_commands/io", CategoryId = "hexparse/commands", NameKey = "hexparse.book.entry.commands.io", DisplayName = "读写", IconItem = "Terraria:Sign", SortNum = 0, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse <代码文本> [重命名]/$：直接解析输入的代码至手持核心；若提供了“重命名”可选参数则会同时重命名核心$(li)$(bold)/hexParse read/$：读取玩家手中的核心，将其内容解析为代码输出至聊天窗口，输出结果点击可复制$(li)$(bold)/hexParse read_signatures/$：同$(bold)read/$，但忽略所有已知图案ID并直接输出其笔划序列" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse clipboard [重命名]/$：读取玩家剪贴板内容，将其作为代码解析至核心；“重命名”可选参数会同时重命名核心$(li)$(bold)/hexParse clipboard_angles [重命名]/$：同上，但只会解析其中形如$(bold)\"wedsaq\"/$的笔划序列段，并将其逐个转为图案" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse clipboard_hexpattern [重命名]/$：（实验性质）同上，但接收 $(bold).hexpattern/$ 格式的文本；$(italic)注：仅支持部分功能/$" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse read_hexbug/$：同$(bold)read/$，但会尝试将格式翻译以适配Discord内HexBug的$(bold)/patterns hex/$命令；$(italic)注：非图案常量、部分HexBug内过时注册名等仍需手动处理/$$(li)$(bold)/hexParse share/$：（实验性质）同$(bold)read/$，但同时广播核心原始内容与解析后代码至服务器内所有玩家" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse mind_stack .../$：从玩家思维栈（法杖施法空间）读写Iota$(li2)$(bold)... peek/$：读取栈内最后一个Iota，若栈为空则得到$(bold)null/$$(li2)$(bold)... push <代码>/$：解析代码并压入思维栈$(li2)$(bold)... push_clipboard/$：同上，但代码来自读取剪贴板" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse property .../$：（$(bold)$(thing)Hexcellular/$联动）向质性Iota读写数据；出于安全性考虑，使用的质性名称会强制添加“_”前缀$(li2)$(bold)... read <质性名>/$：从指定质性读取内容$(li2)$(bold)... write <质性名> <代码>/$：解析代码并写入指定质性$(li2)$(bold)... clipboard <质性名>/$：同上，但代码来自读取剪贴板" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("hexparse/commands");
        if (c != null)
        {
            e = new BookEntry { Id = "hexparse_commands/config", CategoryId = "hexparse/commands", NameKey = "hexparse.book.entry.commands.config", DisplayName = "配置", IconItem = "Terraria:Sign", SortNum = 1, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse (macro/dialect) .../$：管理存储于客户端的别名（dialect，不以$(bold)#/$开头的1对1文本映射）和宏（以$(bold)#/$开头，映射为不定长代码段）$(li2)$(bold)... list/$：列出所有保存的宏/别名$(li2)..." };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li2)$(bold)... define <名称> <内容>/$：定义一组宏/别名，可以为新定义或覆盖已有$(li2)$(bold)macro define_clipboard <名称>/$：同上，但仅对宏可用，读取剪贴板作为宏内容$(li2)$(bold)... remove <名称>/$：移除一个保存的宏/别名（若存在）" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse conflict/$：在不同图案拥有相同短名称（ID路径）时解决冲突$(li2)$(italic)仅在物理客户端（单人游戏、本地联机）或拥有OP权限时启用/$$(li2)$(bold).../$ 或 $(bold)... list/$：列出全部对应多个长ID的短名称$(li2)..." };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li2)$(bold)... list <短名称>/$：列出给定短名称下相互冲突的所有长ID$(li2)$(bold)... set <短名称> <长ID>/$：重定向给定短名称至长图案ID" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("hexparse/commands");
        if (c != null)
        {
            e = new BookEntry { Id = "hexparse_commands/misc", CategoryId = "hexparse/commands", NameKey = "hexparse.book.entry.commands.misc", DisplayName = "杂项 & 帮手", IconItem = "Terraria:Sign", SortNum = 2, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse donate [amount]/$：向自然捐赠等价于指定数量紫水晶粉的媒质；使用于为了使用此mod而产生负罪感的场合 ::)$(li)$(bold)/hexParse learn_great/$：从手持物品内提取卓越法术图案，返回装有解码器本次学习内容的列表" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse lehmer [...数字列表]/$：计算给定排列（从升序出发，如$(bold)0 1 2 3 4/$）对应的Lehmer Code；输入之间需要以空格分隔；所得结果可用于$(l:patterns/stackmanip#hexcasting:swizzle)$(action)骗徒之策略/$" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("hexparse/commands");
        if (c != null)
        {
            e = new BookEntry { Id = "hexparse_commands/op", CategoryId = "hexparse/commands", NameKey = "hexparse.book.entry.commands.op", DisplayName = "OP指令", IconItem = "Terraria:Sign", SortNum = 3, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "$(li)$(bold)/hexParse unlock_great/$$(li2)$(bold)(unlockAll|lockAll|unlock <图案ID>|lock <图案ID>)/$$(li2)配置当前世界的卓越法术解锁状态，子指令分别用于全部解锁、全部锁定与按ID解锁特定" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("patterns");
        if (c != null)
        {
            e = new BookEntry { Id = "patterns/hexparse", CategoryId = "patterns", NameKey = "hexparse.book.entry", DisplayName = "HexParse新增图案", IconItem = "Terraria:Sign", SortNum = 0, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "注释转换", Text = "将输入的注释Iota转换为字符串Iota，或其它内容转换为注释Iota；若未安装$(bold)$(thing)MoreIotas/$则无效果。", PatternId = "hexparse:switch_comment", Anchor = "hexparse:switch_comment", Input = "comment/any", Output = "string/comment" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "编码之策略", Text = "读取我手中的核心，将其内容解析为代码输出至聊天窗口。$(br)只能在法杖内施放。", PatternId = "hexparse:focus2code", Anchor = "hexparse:focus2code", Input = "", Output = "" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "解码之策略", Text = "从剪贴板读取代码，并将其解析至我手持的核心。$(br)只能在法杖内施放。", PatternId = "hexparse:code2focus", Anchor = "hexparse:code2focus", Input = "", Output = "" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "内化卓越法术", Text = "从手持物品（远古卷轴、核心、制成的施法道具等）内提取卓越法术图案，返回装有解码器本次学习内容的列表。", PatternId = "hexparse:learn_patterns", Anchor = "hexparse:learn_patterns", Input = "", Output = "list" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "压缩注释之纯化", Text = "清除列表内所有注释iota，返回处理后的列表。", PatternId = "hexparse:remove_comments", Anchor = "hexparse:remove_comments", Input = "list", Output = "list" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "换行之纯化", Text = "在栈内添加一个具有给定数目空格缩进的换行注释iota。", PatternId = "hexparse:create_linebreak", Anchor = "hexparse:create_linebreak", Input = "num", Output = "comment" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "编译术", Text = "将输入字符串iota编译为iota列表；若未安装$(bold)$(thing)MoreIotas/$则无效果。", PatternId = "hexparse:compile", Anchor = "hexparse:compile", Input = "str", Output = "list" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "捐赠", Text = "向自然捐赠特定数量的媒质（以粉为单位）", PatternId = "hexparse:donate", Anchor = "hexparse:donate", Input = "num", Output = "" };
            e.Pages.Add(p);
        }

        // 进了本体分类的条目按原版的顺序重排（priority 在前，再按 sortnum，再按名字）
        doc.FindCategory("hexparse/commands")?.Entries.Sort(BookEntryOrder.Compare);
        doc.FindCategory("patterns")?.Entries.Sort(BookEntryOrder.Compare);
        doc.RebuildIndex();
    }
}
