// <auto-generated>
//     本文件由 _tools/gen_addon_book.py 生成，**不要手改**：改生成器，然后重新跑脚本。
//     内容：HexDebug 0.9.0+1.20.1（MIT）的书页结构 + 官方简体中文。
// </auto-generated>
#nullable enable
using HexCastingTerraria.Core.Ui;

namespace HexCastingTerraria.Addons.HexDebug.Core;

public static class HexDebugBook
{
    public static void AddTo(BookDocument doc)
    {
        BookCategory? c;
        BookEntry e;
        BookPage p;

        c = doc.FindCategory("greatwork");
        if (c != null)
        {
            e = new BookEntry { Id = "greatwork/quenching_debuggers", CategoryId = "greatwork", NameKey = "hexdebug.category.greatwork.entry.quenching_debuggers", DisplayName = "调试杖的淬灵", IconItem = "QuenchedDebugger", SortNum = 5, Advancement = "hexcasting:enlightenment", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "我的意识已然神化，但我的$(l:items/debugging)工具/$还极为$(italic)低效/$，在卓伟之作的宏大之下愈发脆弱。我需要——不，我$(bold)应得/$——更多。$(br2)悦灵的碎片是改进的绝佳介质。淬灵晶会改变外形、四处跳动，经它们改进的工具也可以——滚动滚轮时按住$(k:sneak)和$(k:sprint)，即可切换当前调试的$(hex)咒术/$槽。" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Crafting, Anchor = "debugger_evaluator", RecipeItem = "QuenchedDebugger" };
            p.RecipeItems.Add("QuenchedDebugger");
            p.RecipeItems.Add("QuenchedEvaluator");
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "hexdebug.category.greatwork.entry.quenching_debuggers.page.2" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "hexdebug.category.greatwork.entry.quenching_debuggers.page.3" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("items");
        if (c != null)
        {
            e = new BookEntry { Id = "items/debugging", CategoryId = "items", NameKey = "hexdebug.category.items.entry.debugging", DisplayName = "调试物品", IconItem = "Debugger", SortNum = 0, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Text, Text = "部分文献中有些不太明确的描述，称古代人会使用一件奇怪的物品协助他们发现复杂$(hex)咒术/$中的问题。我应已成功复刻出了它，定名为$(item)调试杖/$。$(br2)它的工作方式与$(l:items/hexcasting)$(item)造物/$类似。不过，它还能从副手中的物品（比如$(l:items/focus)$(item)核心/$）里直接施放$(hex)咒术/$。$(br2)有些可惜的是，$(item)调试杖/$自身没有太大用处；而为发挥出它的所有潜能，需要先$(l:https://github.com/object-Object/HexDebug/wiki/Setting-up-VSCode-with-HexDebug)准备好/$某种$(l:https://marketplace.visualstudio.com/items?itemName=object-Object.hex-casting)外部工具/$才能正常运作。" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Crafting, Text = "$(italic)哐当！/$$(br2)潜行滚动滚轮还可切换$(item)调试杖/$的各种“步进模式”，操作与$(l:items/spellbook)$(item)法术书/$和$(l:items/abacus)$(item)算盘/$类似。", Anchor = "debugger", RecipeItem = "Debugger" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "我又新制造了一种法杖——$(l:items/debugging#evaluator)$(item)运行杖/$，用以补充$(l:items/debugging#debugger)$(item)调试杖/$的功能。$(br2)调试$(hex)咒术/$时，此法杖绘制的图案会运行于$(l:items/debugging#debugger)$(item)调试杖/$当前的栈和$(l:patterns/readwrite#hexcasting:local)$(thing)渡鸦之思/$。$(br2)清空咒术网格后，$(l:items/debugging#debugger)$(item)调试杖/$似乎会回到$(l:items/debugging#evaluator)$(item)运行杖/$绘制首个图案前的状态。当然，这种操作无法撤回已造成实际影响的法术。" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Crafting, Text = "$(italic)哐啷！/$", Anchor = "evaluator", RecipeItem = "Evaluator" };
            e.Pages.Add(p);
        }

        c = doc.FindCategory("patterns");
        if (c != null)
        {
            e = new BookEntry { Id = "patterns/debugging", CategoryId = "patterns", NameKey = "hexdebug.category.patterns.entry.debugging", DisplayName = "调试图案", IconItem = "Debugger", SortNum = 0, Advancement = "hexcasting:root", EntryColor = -1, Priority = false, Secret = false };
            c.Entries.Add(e);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "调试杖之精思", Text = "若栈由$(l:items/debugging#debugger)$(item)调试杖/$或$(l:items/debugging#evaluator)$(item)运行杖/$执行，则返回 $(thing)True/$；否则返回 $(thing)False/$。", PatternId = "hexdebug:const/debugging", Anchor = "hexdebug:const/debugging", Input = "", Output = "bool" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "认知危害之精思", Text = "向栈顶压入一个$(thing)认知危害/$。", PatternId = "hexdebug:const/cognitohazard", Anchor = "hexdebug:const/cognitohazard", Input = "", Output = "cognitohazard" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Text, Text = "貌似部分$(l:items/debugging#evaluator)调试工具/$在某些$(l:patterns/meta#hexcasting:eval/cc)高等级技术/$中容易导致安全问题。而为解决这一问题，我设计了本图案。$(br2)$(thing)认知危害/$ iota 正常运行时什么都不会发生。不过，如果它出现在$(l:items/debugging#debugger)$(item)调试杖/$执行的$(hex)咒术/$里，那该$(hex)咒术/$便会$(italic)立即/$终止——甚至要先于$(thing)认知危害/$的执行。" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "在前方添加断点", Text = "在运行此图案前，暂停$(l:items/debugging#debugger)$(item)调试杖/$。", PatternId = "hexdebug:breakpoint/before", Anchor = "hexdebug:breakpoint/before", Input = "", Output = "" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "在后方添加断点", Text = "在运行此图案后，也即在运行下一图案之前，暂停$(l:items/debugging#debugger)$(item)调试杖/$。", PatternId = "hexdebug:breakpoint/after", Anchor = "hexdebug:breakpoint/after", Input = "", Output = "" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "制作调试杖", Text = "制作一支能施放$(hex)咒术/$的$(l:items/debugging#debugger)$(item)调试杖/$。这个图案和我之前用过的$(l:patterns/spells/hexcasting)某些图案/$有些相似。$(br2)消耗大约 10 个$(l:items/amethyst)$(item)充能紫水晶/$。", PatternId = "hexdebug:craft/debugger", Anchor = "hexdebug:craft/debugger", Input = "entity, [pattern]", Output = "" };
            e.Pages.Add(p);
            p = new BookPage { Kind = BookPageKind.Pattern, Title = "制作淬灵调试杖", Text = "制作一支能施放$(hex)咒术/$的$(l:greatwork/quenching_debuggers)$(item)淬灵调试杖/$。这个图案和我之前用过的$(l:patterns/spells/hexcasting)某些图案/$有些相似。$(br2)消耗大约 10 个$(l:items/amethyst)$(item)充能紫水晶/$。", PatternId = "hexdebug:craft/quenched_debugger", Anchor = "hexdebug:craft/quenched_debugger", Input = "entity, [pattern]", Output = "" };
            e.Pages.Add(p);
        }

        // 进了本体分类的条目按原版的顺序重排（priority 在前，再按 sortnum，再按名字）
        doc.FindCategory("greatwork")?.Entries.Sort(BookEntryOrder.Compare);
        doc.FindCategory("items")?.Entries.Sort(BookEntryOrder.Compare);
        doc.FindCategory("patterns")?.Entries.Sort(BookEntryOrder.Compare);
        doc.RebuildIndex();
    }
}
