// <auto-generated>
//     本文件由 _tools/gen_deco_blocks.ps1 生成，**不要手改**：
//     改表里的那一行，然后重新跑脚本。手改会在下次生成时被覆盖。
// </auto-generated>
using HexCastingTerraria.Content.Items;
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace HexCastingTerraria.Content.Tiles;

/// <summary>
/// 建材方块的公共实现（P2-6 装饰方块家族）。
///
/// 每个子类只声明「自己和别人有什么不同」（颜色 / 镐力 / 尘 / 掉落），
/// 其余行为完全一致。子类由脚本生成，见文件头。
/// </summary>
public abstract class HexDecoBlock : ModTile
{
    /// <summary>小地图上的颜色。</summary>
    protected abstract Color MapColor { get; }

    /// <summary>挖掘所需镐力。0 = 任意镐；1 = 梦魇镐以上；2 = 精金镐以上。</summary>
    protected virtual int RequiredPick => 0;

    /// <summary>挖掘时的尘埃。</summary>
    protected virtual int BlockDust => DustID.Stone;

    /// <summary>是否阻挡光线（树叶这类不该挡）。</summary>
    protected virtual bool BlocksLight => true;

    public override void SetStaticDefaults()
    {
        Main.tileSolid[Type] = true;
        Main.tileBlockLight[Type] = BlocksLight;
        Main.tileMergeDirt[Type] = false;
        Main.tileLighted[Type] = false;

        MinPick = RequiredPick;
        DustType = BlockDust;
        HitSound = SoundID.Tink;
        AddMapEntry(MapColor);
    }
}

/// <summary>板岩块。对应源项目 `hexcasting:slate_block`。</summary>
public sealed class SlateBlock : HexDecoBlock
{
    protected override Color MapColor => new(70, 66, 84);
}

/// <summary>板岩块（物品形态）。</summary>
public sealed class SlateBlockItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateBlock>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 281 ringAll(深板岩, 紫水晶粉)：8 深板岩环 + 1 粉 → 8 板岩块
        CreateRecipe(8)
            .AddIngredient(ItemID.StoneBlock, 8)
            .AddIngredient<AmethystDust>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>板岩瓦。对应源项目 `hexcasting:slate_tiles`。</summary>
public sealed class SlateTiles : HexDecoBlock
{
    protected override Color MapColor => new(74, 70, 90);
}

/// <summary>板岩瓦（物品形态）。</summary>
public sealed class SlateTilesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateTiles>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 stoneSet：瓦 ×4 ← 砖 ×4（**不是**基底块）
        CreateRecipe(4)
            .AddIngredient<SlateBricksItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.SlateBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>板岩砖。对应源项目 `hexcasting:slate_bricks`。</summary>
public sealed class SlateBricks : HexDecoBlock
{
    protected override Color MapColor => new(78, 72, 94);
}

/// <summary>板岩砖（物品形态）。</summary>
public sealed class SlateBricksItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateBricks>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 stoneSet：板岩砖 ×4 ← 板岩基底块 ×4
        CreateRecipe(4)
            .AddIngredient<SlateBlockItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneSet：砖 ×1 ← 小砖 ×1（回炉，HexplatRecipes.java:615）
        CreateRecipe()
            .AddIngredient<SlateBricksSmallItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1（泰拉 = 重型工作台）
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.SlateBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>小板岩砖。对应源项目 `hexcasting:slate_bricks_small`。</summary>
public sealed class SlateBricksSmall : HexDecoBlock
{
    protected override Color MapColor => new(82, 76, 98);
}

/// <summary>小板岩砖（物品形态）。</summary>
public sealed class SlateBricksSmallItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateBricksSmall>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 stoneSet：小砖 ×1 ← 砖 ×1（切细）
        CreateRecipe()
            .AddIngredient<SlateBricksItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.SlateBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>板岩柱。对应源项目 `hexcasting:slate_pillar`。</summary>
public sealed class SlatePillar : HexDecoBlock
{
    protected override Color MapColor => new(76, 70, 92);
}

/// <summary>板岩柱（物品形态）。</summary>
public sealed class SlatePillarItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlatePillar>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 stoneSet：板岩柱 ×2 ← 板岩基底块 ×2
        CreateRecipe(2)
            .AddIngredient<SlateBlockItem>(2)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.SlateBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>板岩紫晶瓦。对应源项目 `hexcasting:slate_amethyst_tiles`。</summary>
public sealed class SlateAmethystTiles : HexDecoBlock
{
    protected override Color MapColor => new(96, 80, 110);
}

/// <summary>板岩紫晶瓦（物品形态）。</summary>
public sealed class SlateAmethystTilesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateAmethystTiles>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 441-459：SlateTiles + AmethystTiles → 2（板岩与紫晶同款混料）
        CreateRecipe(2)
            .AddIngredient<SlateTilesItem>(1)
            .AddIngredient<AmethystTilesItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>板岩紫晶砖。对应源项目 `hexcasting:slate_amethyst_bricks`。</summary>
public sealed class SlateAmethystBricks : HexDecoBlock
{
    protected override Color MapColor => new(100, 84, 114);
}

/// <summary>板岩紫晶砖（物品形态）。</summary>
public sealed class SlateAmethystBricksItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateAmethystBricks>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 441-459：SlateBricks + AmethystBricks → 2（板岩与紫晶同款混料）
        CreateRecipe(2)
            .AddIngredient<SlateBricksItem>(1)
            .AddIngredient<AmethystBricksItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>小板岩紫晶砖。对应源项目 `hexcasting:slate_amethyst_bricks_small`。</summary>
public sealed class SlateAmethystBricksSmall : HexDecoBlock
{
    protected override Color MapColor => new(104, 88, 118);
}

/// <summary>小板岩紫晶砖（物品形态）。</summary>
public sealed class SlateAmethystBricksSmallItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateAmethystBricksSmall>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 441-459：SlateBricksSmall + AmethystBricksSmall → 2（板岩与紫晶同款混料）
        CreateRecipe(2)
            .AddIngredient<SlateBricksSmallItem>(1)
            .AddIngredient<AmethystBricksSmallItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>板岩紫晶柱。对应源项目 `hexcasting:slate_amethyst_pillar`。</summary>
public sealed class SlateAmethystPillar : HexDecoBlock
{
    protected override Color MapColor => new(98, 82, 112);
}

/// <summary>板岩紫晶柱（物品形态）。</summary>
public sealed class SlateAmethystPillarItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<SlateAmethystPillar>();
    protected override int ItemRarity => ItemRarityID.White;

    public override void AddRecipes()
    {
        // 源 441-459：SlatePillar + AmethystPillar → 2（板岩与紫晶同款混料）
        CreateRecipe(2)
            .AddIngredient<SlatePillarItem>(1)
            .AddIngredient<AmethystPillarItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>紫晶瓦。对应源项目 `hexcasting:amethyst_tiles`。</summary>
public sealed class AmethystTiles : HexDecoBlock
{
    protected override Color MapColor => new(138, 112, 176);
}

/// <summary>紫晶瓦（物品形态）。</summary>
public sealed class AmethystTilesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AmethystTiles>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 stoneSet：瓦 ×4 ← 砖 ×4（**不是**基底块）
        CreateRecipe(4)
            .AddIngredient<AmethystBricksItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.AmethystBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>紫晶砖。对应源项目 `hexcasting:amethyst_bricks`。</summary>
public sealed class AmethystBricks : HexDecoBlock
{
    protected override Color MapColor => new(144, 118, 182);
}

/// <summary>紫晶砖（物品形态）。</summary>
public sealed class AmethystBricksItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AmethystBricks>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 stoneSet：紫晶砖 ×4 ← 紫晶基底块 ×4
        CreateRecipe(4)
            .AddIngredient<AmethystDustBlockItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneSet：砖 ×1 ← 小砖 ×1（回炉，HexplatRecipes.java:615）
        CreateRecipe()
            .AddIngredient<AmethystBricksSmallItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1（泰拉 = 重型工作台）
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.AmethystBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>小紫晶砖。对应源项目 `hexcasting:amethyst_bricks_small`。</summary>
public sealed class AmethystBricksSmall : HexDecoBlock
{
    protected override Color MapColor => new(150, 124, 188);
}

/// <summary>小紫晶砖（物品形态）。</summary>
public sealed class AmethystBricksSmallItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AmethystBricksSmall>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 stoneSet：小砖 ×1 ← 砖 ×1（切细）
        CreateRecipe()
            .AddIngredient<AmethystBricksItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.AmethystBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>紫晶柱。对应源项目 `hexcasting:amethyst_pillar`。</summary>
public sealed class AmethystPillar : HexDecoBlock
{
    protected override Color MapColor => new(140, 114, 178);
}

/// <summary>紫晶柱（物品形态）。</summary>
public sealed class AmethystPillarItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AmethystPillar>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 stoneSet：紫晶柱 ×2 ← 紫晶基底块 ×2
        CreateRecipe(2)
            .AddIngredient<AmethystDustBlockItem>(2)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.AmethystBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>淬灵块。对应源项目 `hexcasting:quenched_allay`。</summary>
public sealed class QuenchedAllay : HexDecoBlock
{
    protected override Color MapColor => new(104, 168, 178);
    protected override int RequiredPick => 1;
}

/// <summary>淬灵块（物品形态）。</summary>
public sealed class QuenchedAllayItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<QuenchedAllay>();
    protected override int ItemRarity => ItemRarityID.Pink;

    public override void AddRecipes()
    {
        // 源：脑叶切除（紫水晶块 + 悦灵）→ 淬灵块 1:1；泰拉由淬灵晶碎片还原
        CreateRecipe()
            .AddIngredient<QuenchedAllayShard>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>淬灵瓦。对应源项目 `hexcasting:quenched_allay_tiles`。</summary>
public sealed class QuenchedAllayTiles : HexDecoBlock
{
    protected override Color MapColor => new(108, 174, 184);
    protected override int RequiredPick => 1;
}

/// <summary>淬灵瓦（物品形态）。</summary>
public sealed class QuenchedAllayTilesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<QuenchedAllayTiles>();
    protected override int ItemRarity => ItemRarityID.Pink;

    public override void AddRecipes()
    {
        // 源 stoneSet：瓦 ×4 ← 砖 ×4（**不是**基底块）
        CreateRecipe(4)
            .AddIngredient<QuenchedAllayBricksItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.QuenchedAllayBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>淬灵砖。对应源项目 `hexcasting:quenched_allay_bricks`。</summary>
public sealed class QuenchedAllayBricks : HexDecoBlock
{
    protected override Color MapColor => new(112, 180, 190);
    protected override int RequiredPick => 1;
}

/// <summary>淬灵砖（物品形态）。</summary>
public sealed class QuenchedAllayBricksItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<QuenchedAllayBricks>();
    protected override int ItemRarity => ItemRarityID.Pink;

    public override void AddRecipes()
    {
        // 源 stoneSet：淬灵砖 ×4 ← 淬灵基底块 ×4
        CreateRecipe(4)
            .AddIngredient<QuenchedAllayItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneSet：砖 ×1 ← 小砖 ×1（回炉，HexplatRecipes.java:615）
        CreateRecipe()
            .AddIngredient<QuenchedAllayBricksSmallItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1（泰拉 = 重型工作台）
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.QuenchedAllayBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>小淬灵砖。对应源项目 `hexcasting:quenched_allay_bricks_small`。</summary>
public sealed class QuenchedAllayBricksSmall : HexDecoBlock
{
    protected override Color MapColor => new(116, 186, 196);
    protected override int RequiredPick => 1;
}

/// <summary>小淬灵砖（物品形态）。</summary>
public sealed class QuenchedAllayBricksSmallItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<QuenchedAllayBricksSmall>();
    protected override int ItemRarity => ItemRarityID.Pink;

    public override void AddRecipes()
    {
        // 源 stoneSet：小砖 ×1 ← 砖 ×1（切细）
        CreateRecipe()
            .AddIngredient<QuenchedAllayBricksItem>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

        // 源 stoneCutterFromTag：切石机 1:1
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.QuenchedAllayBlocks, 1)
            .AddTile(TileID.HeavyWorkBench)
            .Register();

    }
}

/// <summary>启迪原木。对应源项目 `hexcasting:edified_log`。</summary>
public sealed class EdifiedLog : HexDecoBlock
{
    protected override Color MapColor => new(96, 84, 66);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>启迪原木（物品形态）。</summary>
public sealed class EdifiedLogItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedLog>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源：Edify 把树苗变成启迪树苗 → 阿卡夏树（**无配方**）→ 这里给 1:1 保底转化
        CreateRecipe()
            .AddRecipeGroup(RecipeGroups.Wood, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>紫晶启迪原木。对应源项目 `hexcasting:edified_log_amethyst`。</summary>
public sealed class EdifiedLogAmethyst : HexDecoBlock
{
    protected override Color MapColor => new(100, 84, 78);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>紫晶启迪原木（物品形态）。</summary>
public sealed class EdifiedLogAmethystItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedLogAmethyst>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 彩色启迪原木（嵌紫晶）；源项目来自不同树种的阿卡夏树，泰拉用宝石定色
        CreateRecipe()
            .AddIngredient<EdifiedLogItem>(1)
            .AddIngredient(ItemID.Amethyst, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>东陵启迪原木。对应源项目 `hexcasting:edified_log_aventurine`。</summary>
public sealed class EdifiedLogAventurine : HexDecoBlock
{
    protected override Color MapColor => new(94, 90, 68);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>东陵启迪原木（物品形态）。</summary>
public sealed class EdifiedLogAventurineItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedLogAventurine>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 彩色启迪原木（嵌翡翠 ≈ 东陵玉，同色系、同为肉前宝石）
        CreateRecipe()
            .AddIngredient<EdifiedLogItem>(1)
            .AddIngredient(ItemID.Emerald, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>黄晶启迪原木。对应源项目 `hexcasting:edified_log_citrine`。</summary>
public sealed class EdifiedLogCitrine : HexDecoBlock
{
    protected override Color MapColor => new(104, 92, 62);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>黄晶启迪原木（物品形态）。</summary>
public sealed class EdifiedLogCitrineItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedLogCitrine>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 彩色启迪原木（嵌黄玉 ≈ 黄晶，同色系、同为肉前宝石）
        CreateRecipe()
            .AddIngredient<EdifiedLogItem>(1)
            .AddIngredient(ItemID.Topaz, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>紫启迪原木。对应源项目 `hexcasting:edified_log_purple`。</summary>
public sealed class EdifiedLogPurple : HexDecoBlock
{
    protected override Color MapColor => new(92, 80, 74);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>紫启迪原木（物品形态）。</summary>
public sealed class EdifiedLogPurpleItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedLogPurple>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 彩色启迪原木（嵌紫水晶粉）
        CreateRecipe()
            .AddIngredient<EdifiedLogItem>(1)
            .AddIngredient<AmethystDust>(1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>去皮启迪原木。对应源项目 `hexcasting:stripped_edified_log`。</summary>
public sealed class StrippedEdifiedLog : HexDecoBlock
{
    protected override Color MapColor => new(120, 108, 88);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>去皮启迪原木（物品形态）。</summary>
public sealed class StrippedEdifiedLogItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<StrippedEdifiedLog>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 HexStrippables：5 种启迪原木都去皮成同一种（tag 输入）
        CreateRecipe()
            .AddRecipeGroup(HexRecipeGroups.EdifiedLogs, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>启迪木。对应源项目 `hexcasting:edified_wood`。</summary>
public sealed class EdifiedWood : HexDecoBlock
{
    protected override Color MapColor => new(96, 84, 66);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>启迪木（物品形态）。</summary>
public sealed class EdifiedWoodItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedWood>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 319-323：启迪木 ×3 ← 启迪原木 ×4
        CreateRecipe(3)
            .AddIngredient<EdifiedLogItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>去皮启迪木。对应源项目 `hexcasting:stripped_edified_wood`。</summary>
public sealed class StrippedEdifiedWood : HexDecoBlock
{
    protected override Color MapColor => new(120, 108, 88);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>去皮启迪木（物品形态）。</summary>
public sealed class StrippedEdifiedWoodItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<StrippedEdifiedWood>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 319-323：去皮启迪木 ×3 ← 去皮启迪原木 ×4
        CreateRecipe(3)
            .AddIngredient<StrippedEdifiedLogItem>(4)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>启迪木板。对应源项目 `hexcasting:edified_planks`。</summary>
public sealed class EdifiedPlanks : HexDecoBlock
{
    protected override Color MapColor => new(132, 118, 92);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>启迪木板（物品形态）。</summary>
public sealed class EdifiedPlanksItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedPlanks>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 312-314：启迪木板 ×4 ← 1 个任意启迪原木（tag）
        CreateRecipe(4)
            .AddRecipeGroup(HexRecipeGroups.EdifiedLogs, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>启迪木面板。对应源项目 `hexcasting:edified_panel`。</summary>
public sealed class EdifiedPanel : HexDecoBlock
{
    protected override Color MapColor => new(138, 124, 98);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>启迪木面板（物品形态）。</summary>
public sealed class EdifiedPanelItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedPanel>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 326-331：面板 ×9 ← 启迪木板 ×9
        CreateRecipe(9)
            .AddIngredient<EdifiedPlanksItem>(9)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>启迪木瓷砖。对应源项目 `hexcasting:edified_tile`。</summary>
public sealed class EdifiedTile : HexDecoBlock
{
    protected override Color MapColor => new(142, 128, 102);
    protected override int BlockDust => DustID.WoodFurniture;
}

/// <summary>启迪木瓷砖（物品形态）。</summary>
public sealed class EdifiedTileItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<EdifiedTile>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源 333-338：瓷砖 ×6 ← 启迪木板 ×6
        CreateRecipe(6)
            .AddIngredient<EdifiedPlanksItem>(6)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>紫晶启迪树叶。对应源项目 `hexcasting:amethyst_edified_leaves`。</summary>
public sealed class AmethystEdifiedLeaves : HexDecoBlock
{
    protected override Color MapColor => new(122, 100, 150);
    protected override int BlockDust => DustID.Grass;
    protected override bool BlocksLight => false;
}

/// <summary>紫晶启迪树叶（物品形态）。</summary>
public sealed class AmethystEdifiedLeavesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AmethystEdifiedLeaves>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源：树叶由 Edify 转化（**无配方**）→ 保底：启迪木板定形 + 宝石定色
        CreateRecipe(4)
            .AddIngredient<EdifiedPlanksItem>(1)
            .AddIngredient(ItemID.Amethyst, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>东陵启迪树叶。对应源项目 `hexcasting:aventurine_edified_leaves`。</summary>
public sealed class AventurineEdifiedLeaves : HexDecoBlock
{
    protected override Color MapColor => new(112, 122, 96);
    protected override int BlockDust => DustID.Grass;
    protected override bool BlocksLight => false;
}

/// <summary>东陵启迪树叶（物品形态）。</summary>
public sealed class AventurineEdifiedLeavesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<AventurineEdifiedLeaves>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源：树叶由 Edify 转化（**无配方**）→ 保底同上
        CreateRecipe(4)
            .AddIngredient<EdifiedPlanksItem>(1)
            .AddIngredient(ItemID.Emerald, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

/// <summary>黄晶启迪树叶。对应源项目 `hexcasting:citrine_edified_leaves`。</summary>
public sealed class CitrineEdifiedLeaves : HexDecoBlock
{
    protected override Color MapColor => new(134, 120, 88);
    protected override int BlockDust => DustID.Grass;
    protected override bool BlocksLight => false;
}

/// <summary>黄晶启迪树叶（物品形态）。</summary>
public sealed class CitrineEdifiedLeavesItem : HexDecoBlockItem
{
    public override int TileType => ModContent.TileType<CitrineEdifiedLeaves>();
    protected override int ItemRarity => ItemRarityID.Blue;

    public override void AddRecipes()
    {
        // 源：树叶由 Edify 转化（**无配方**）→ 保底同上
        CreateRecipe(4)
            .AddIngredient<EdifiedPlanksItem>(1)
            .AddIngredient(ItemID.Topaz, 1)
            .AddTile(TileID.WorkBenches)
            .Register();

    }
}

